# -- 코드를 입력하세요
SELECT B.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM
(SELECT ANIMAL_ID, NAME, SEX_UPON_INTAKE
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE 'Intact%') A
JOIN 
ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.SEX_UPON_OUTCOME LIKE 'Neutered Male' OR B.SEX_UPON_OUTCOME LIKE 'Spayed Female'
ORDER BY ANIMAL_ID