-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME,A.AP *B.BP AS TOTAL_SALES
FROM  (SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE)AS AP FROM FOOD_PRODUCT GROUP BY PRODUCT_NAME) A
JOIN
  (SELECT PRODUCT_ID, SUM(AMOUNT) AS BP FROM FOOD_ORDER WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31' GROUP BY PRODUCT_ID) B
  ON A.PRODUCT_ID = B.PRODUCT_ID
  GROUP BY A.PRODUCT_NAME
  ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
    