
SELECT INGREDIENT_TYPE, sum(f.total_order) as TOTAL_ORDER 
FROM FIRST_HALF F JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE I.INGREDIENT_TYPE in('sugar_based', 'fruit_based')
GROUP BY INGREDIENT_TYPE